spring:
  application:
    name: skinfit
  profiles:
    active: dev  # 또는 prod (운영 환경의 경우)
    group:
      dev:
        - mail
        - oauth
      prod:
        - mail
        - oauth
      default: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

jwt:
  access-token-expiration: 1800000
  refresh-token-expiration: 604800000
