spring:
  application:
    name: skinfit
  data:
    redis:
      host: redis
      port: 6379
      password: your_redis_password
  datasource:
    url: jdbc:mysql://mysql:3306/skinfit?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: your_db_username
    password: your_db_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

security:
  require-ssl: true

jwt:
  secret-key: your_jwt_secret_key
  access-token-expiration: 1800000
  refresh-token-expiration: 604800000

logging:
  level:
    root: ERROR
    com.yourpackage.skinfit: INFO

# EC2 안전한 위치에 생성 후 젠킨스와 마운트 해줘야 한다.